apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-demo-deployment
  labels:
    app: cassandra-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-demo
  template:
    metadata:
      labels:
        app: cassandra-demo
    spec:
      containers:
        - name: cassandra-demo
          image: qiusuo/cassandra-demo:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-demo-svc
spec:
  ports:
    - name: 8090-8090
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: cassandra-demo
  sessionAffinity: None
  type: ClusterIP

